### ISSUE TITLE
Can't open/read some epub files.

### ISSUE THREAD

**Issue by fluffyloopy** [lellid/LediReader#2]
![image](https://user-images.githubusercontent.com/36381994/153009098-d62c4be3-65ed-44b4-b350-8667a4696665.png)

**Comment by lellid** [comment]
I will look into it... In the meantime you can try to convert this ebook to .docx and then back to .epub.
Sorry for the inconvenience.

**Comment by fluffyloopy** [comment]
so, it sometimes works. sometimes doesnt. i have no idea why. i had to restart pc and try to open it properly
